services:
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
    volumes:
      - ./zk-data:/data
      - ./zk-datalog:/datalog
    restart: always

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka-broker
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAIN_TEXT_LISTENER=yes
      - KAFKA_LISTERBERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    volumes:
      - ./kafka-data:/bitnami/kafka
    restart: always
    depends_on:
      - zookeeper

volumes:
  zk-data:
    driver: local
  kafka-data:
    driver: local
  

      
    
    